### ISSUE TITLE
Pluggable uStreamer implementation

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-streamer-rust#2]
- Plugable uStreamer (so we can connect it to other uPlatforms)
Intended to run in Ubuntu for initial version

**Comment by PLeVasseur** [comment]
I think we can amend this as so:
> * ~uSubscription, uDiscovery, uTwin servces~
> * Plugable uStreamer (so we can connect it to other uPlatforms)
Intended to run in Ubuntu for initial version

Since this repo will only hold the streamer now.

Could rename to, I suppose. Maybe... "`up-streamer-rust` initial implementation" or something to that effect?

**Comment by PLeVasseur** [comment]
Could rename to `Initial Implementation of up-streamer-rust for Publish messages`

**Comment by PLeVasseur** [comment]
Completed by #8
