### ISSUE TITLE
Error handling when register_listener fails 

### ISSUE THREAD

**Issue by jjj-vtm** [eclipse-uprotocol/up-streamer-rust#21]
If register_listener fails there is only a log message 

https://github.com/eclipse-uprotocol/up-streamer-rust/blob/d4ab17fbc745705290e29e5251fa8e9fcbffe943/up-streamer/src/ustreamer.rs#L153C1-L173

but the constructed tuple is added to forwarding_listeners and set to active. This basically leaves a "dead" listener in the HashMap.

**Comment by PLeVasseur** [comment]
Thanks for pointing this out! You're completely right :)

**Comment by pranavishere2** [comment]
@PLeVasseur  Please assign this to me

**Comment by PLeVasseur** [comment]
@pranavishere2 -- you mentioned yesterday some refactoring done in this area fixed this issue.

Could you update here with info on how it was solved?

Perhaps you could also write a test to prove this out.

**Comment by pranavishere2** [comment]
**Prior to the update in the main branch, the following code was leading to a dead listener object even when registerListener failed:**
if let Err(err) = reg_res {
    warn!("{FORWARDING_LISTENERS_TAG}:{FORWARDING_LISTENERS_FN_INSERT_TAG} unable to register listener, error: {err}");
} else {
    debug!("{FORWARDING_LISTENERS_TAG}:{FORWARDING_LISTENERS_FN_INSERT_TAG} able to register listener");
}

(
    0,
    forwarding_listener,
)

**Following the refactoring in the main branch, this issue has been resolved by introducing an exception when the registerListener call fails. The updated implementation ensures that if the listener cannot be registered, an error is thrown to prevent the dead listener object. Below is the code snippet:**

uuris_to_backpedal.insert((any_uuri(), Some(uauthority_to_uuri(out_authority))));
if let Err(err) = in_transport
    .register_listener(
        &any_uuri(),
        Some(&uauthority_to_uuri(out_authority)),
        forwarding_listener.clone(),
    )
    .await
{
    warn!(
        "{}:{} unable to register request listener, error: {}",
        FORWARDING_LISTENERS_TAG, FORWARDING_LISTENERS_FN_INSERT_TAG, err
    );
    for uuri_pair in &uuris_to_backpedal {
        if let Err(err) = in_transport
            .unregister_listener(
                &uuri_pair.0,
                uuri_pair.1.as_ref(),
                forwarding_listener.clone(),
            )
            .await
        {
            warn!(
                "{}:{} unable to unregister listener, error: {}",
                FORWARDING_LISTENERS_TAG, FORWARDING_LISTENERS_FN_INSERT_TAG, err
            );
        }
    }
    return Err(ForwardingListenerError::FailToRegisterNotificationRequestResponseListener);
}

**Also the listener is added in the map at the end of the function only when all preconditions are satisfied:**
        forwarding_listeners.insert(
            (in_comparable_transport, out_authority.to_string()),
            (1, forwarding_listener.clone()),
        );
        Ok(Some(forwarding_listener))

This makes sure there will not be any dead listner when registerListener API fails.

**Comment by PLeVasseur** [comment]
@pranavishere2 -- please use code tags to put the code in and give references to the main branch which files / lines, i.e. use links.

**Comment by pranavishere2** [comment]
> @pranavishere2 -- please use code tags to put the code in and give references to the main branch which files / lines, i.e. use links.

Done

**Comment by PLeVasseur** [comment]
Thanks @pranavishere2 -- closing as completed by #20
