### ISSUE TITLE
Zenoh uPlatform: uStreamer Skeleton

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-streamer-rust#3]
Initial commit of the Zenoh based Linux uPlatform. This will just be the structure and initial code, it will depend on the initial commit of

**Comment by PLeVasseur** [comment]
Hey there, I could pick this one up 😄

**Comment by PLeVasseur** [comment]
Fleshing out my thoughts here a bit more, this would be:
* Skeleton, but maybe not all the kinks worked out yet
* Fair amount of routing logic
* Missing some functionality around controlling the streamer after it's kicked off (e.g. stopping, adding more routes, etc)

WDYT  @stevenhartley?

**Comment by PLeVasseur** [comment]
Could rename to `Initial Implementation of up-streamer-rust for Request, Response, Notification messages`

**Comment by PLeVasseur** [comment]
Completed by #8
